### ISSUE TITLE
Aseman RegularApp Example android build error

### ISSUE THREAD

**Issue by ssakone** [Aseman-Land/QtAseman#11]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/as_c/Dev/QtAseman/demos/build-RegularApp-Android_for_armeabi_v7a_arm64_v8a_x86_x86_64_Clang_Qt_5_15_0_for_Android-Debug/android-build/AndroidManifest.xml:21:13-120: AAPT: error: resource array/bundled_in_lib (aka co.aseman.demo.regular:array/bundled_in_lib) not found.
         
     /home/as_c/Dev/QtAseman/demos/build-RegularApp-Android_for_armeabi_v7a_arm64_v8a_x86_x86_64_Clang_Qt_5_15_0_for_Android-Debug/android-build/AndroidManifest.xml:22:13-126: AAPT: error: resource array/bundled_in_assets (aka co.aseman.demo.regular:array/bundled_in_assets) not found.
         `

**Comment by Lee-Feng** [comment]
maybe I have already solved this problem. see [pull request](https://github.com/Aseman-Land/QtAseman/pull/13)
