### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ZoraDomain** [Aseman-Land/QtAseman#7]
Hi.
This project look very interesting. I have the next error when want to install by the rule.
![Screenshot from 2020-06-16 11-04-09](https://user-images.githubusercontent.com/35845465/84792149-8b5e8d80-afc1-11ea-926a-7d10681cc5fd.png)

it's like it didn't appear in the apt. I am really neophyte with this.

**Comment by ZoraDomain** [comment]
And, if i install by the other side, appear the next error: 
![Screenshot from 2020-06-16 11-12-36](https://user-images.githubusercontent.com/35845465/84792953-82ba8700-afc2-11ea-8e6a-65d732b54dce.png)

**Comment by realbardia** [comment]
Hi
What's the version of ubuntu, you use? Launchpad repository supports ubuntu 20.04 only.
And about QtCreator, This is not important error. this file do not build and just copied as a template for QtCreator. Build it in release mode and the run `make install` command.

**Comment by ZoraDomain** [comment]
Thank you very much friend.
