### ISSUE TITLE
Error when build in android

### ISSUE THREAD

**Issue by ZoraDomain** [Aseman-Land/QtAseman#8]
Hi guys

The library work outstanding with desktop kits but when i try to build regular app demo i have the next error.
![Screenshot from 2020-06-26 14-37-44](https://user-images.githubusercontent.com/35845465/85890256-ffb3e080-b7ba-11ea-99f0-c76b9aa19f2b.png)

I use Ubuntu 16.04 LTS and i compile with android armabi-v7a with Android build SDK android-27.

Greetings from Dominican Republic

**Comment by realbardia** [comment]
Hi
Thank you for reporting :)
There was some API used in the android parts needs some android dependencies. We removed them and change them to optional in the last commit.
